export enum ProjectState {
  DRAFT = 'draft',
  MAQUETTE = 'MAQUETTE',
  VALIDATION_MAQUETTE = 'VALIDATION_MAQUETTE',
  DEVELOPMENT = 'DEVELOPMENT',
  REVIEW = 'REVIEW',
  TESTING = 'TESTING',
  CLIENT_VALIDATION = 'CLIENT_VALIDATION',
  COMPLETED = 'COMPLETED'
} 